language: php

php:
  - 7.1
  - 7.2

before_install: composer self-update

install: composer install --prefer-source --no-interaction --dev

script: ./vendor/bin/phpunit

jobs:
  include:
    - stage: GitHub Pages
      php: 7.1
      before_install:
        - curl -o ~/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.11/nvm.sh
        - bash -c "source ~/.nvm/nvm.sh; nvm install node; node --version"
      install: npm install
      script: npm run docs:build
      deploy:
        local-dir: docs/.vuepress/dist
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
